import 'package:i18n_extension/i18n_extension.dart';
import 'package:voiceClient/constants/strings.dart';
extension Localization on String {
static final _t = Translations('en') +
{
'en': Strings.MFV,
'zh': '我的家庭之声',
'de': 'Meine Familienstimme',
'hi': 'मेरी पारिवारिक आवाज',
'id': 'Suara Keluarga Saya',
'ja': '私の家族の声',
'ko': '내 가족의 목소리',
'pt': 'Minha Voz de Família',
'ru': 'Голос моей семьи',
'es': 'My Family Voice',
} +
{
'en': Strings.ok,
'zh': '好',
'de': 'in Ordnung',
'hi': 'ठीक',
'id': 'baik',
'ja': 'わかりました',
'ko': '그래',
'pt': 'Okey',
'ru': 'Хорошо',
'es': 'De acuerdo',
} +
{
'en': Strings.cancel,
'zh': '取消',
'de': 'Stornieren',
'hi': 'रद्द करना',
'id': 'Membatalkan',
'ja': 'キャンセル',
'ko': '취소',
'pt': 'Cancelar',
'ru': 'Отмена',
'es': 'Cancelar',
} +
{
'en': Strings.areYouSure,
'zh': '你确定吗？',
'de': 'Bist du sicher?',
'hi': 'क्या आपको यकीन है?',
'id': 'Apakah kamu yakin',
'ja': '確かですか。',
'ko': '확실한가요?',
'pt': 'Tem certeza?',
'ru': 'Уверен?',
'es': '¿Estás seguro?',
} +
{
'en': Strings.yes,
'zh': '是',
'de': 'Ja',
'hi': 'हाँ',
'id': 'Iya',
'ja': 'はい',
'ko': '예',
'pt': 'Sim',
'ru': 'Да',
'es': 'Sí',
} +
{
'en': Strings.noResults,
'zh': '没结果',
'de': 'Keine Ergebnisse',
'hi': 'कोई परिणाम नहीं',
'id': 'Tidak ada hasil',
'ja': '結果なし',
'ko': '결과 없음',
'pt': 'Sem resultados',
'ru': 'Нет результатов',
'es': 'Sin resultados',
} +
{
'en': Strings.upload,
'zh': '上载',
'de': 'Hochladen',
'hi': 'डालना',
'id': 'Unggah',
'ja': 'アップロード',
'ko': '업로드',
'pt': 'Carregar',
'ru': 'Загрузить',
'es': 'Subir',
} +
{
'en': Strings.loadMore,
'zh': '装载更多',
'de': 'Mehr laden',
'hi': 'और लोड करें',
'id': 'Muat lebih banyak',
'ja': 'より多くの読み込み',
'ko': '더 많은 로드',
'pt': 'Carregar mais',
'ru': 'Загрузите больше',
'es': 'Cargar más',
} +
{
'en': Strings.logout,
'zh': '登出',
'de': 'Ausloggen',
'hi': 'लॉग आउट',
'id': 'Keluar',
'ja': 'ログアウト',
'ko': 'Logout',
'pt': 'Logout',
'ru': 'Выход',
'es': 'Cerrar sesión',
} +
{
'en': Strings.logoutAreYouSure,
'zh': '您确定要注销吗？',
'de': 'Sind Sie sicher, dass Sie sich abmelden möchten?',
'hi': 'क्या आप वाकई लॉगआउट करना चाहते हैं?',
'id': 'Anda yakin ingin keluar?',
'ja': 'ログアウトしますか?',
'ko': '로그아웃하시겠습니까?',
'pt': 'Tem certeza que quer se dizer?',
'ru': 'Вы уверены, что вы хотите, чтобы логотип?',
'es': '¿Está seguro de que desea cerrar la sesión?',
} +
{
'en': Strings.logoutFailed,
'zh': '登出失败',
'de': 'Abmeldung fehlgeschlagen',
'hi': 'लॉगआउट विफल रहा',
'id': 'Keluar gagal',
'ja': 'ログアウトに失敗しました',
'ko': '로그아웃 실패',
'pt': 'Logout falhou',
'ru': 'Логут потерпел неудачу',
'es': 'Error al cerrar la sesión',
} +
{
'en': Strings.zhLocale,
'zh': '中文',
'de': 'Chinesisch',
'hi': 'चीनी',
'id': 'Cina',
'ja': '中国語',
'ko': '중국어',
'pt': 'Chinês',
'ru': 'китайский',
'es': 'Chino',
} +
{
'en': Strings.usLocale,
'zh': '英语',
'de': 'Englisch',
'hi': 'अंग्रेज़ी',
'id': 'Inggris',
'ja': '英語',
'ko': '영어',
'pt': 'Inglês',
'ru': 'английский',
'es': 'Inglés',
} +
{
'en': Strings.deLocale,
'zh': '德语',
'de': 'Deutsche',
'hi': 'जर्मन',
'id': 'Jerman',
'ja': 'ドイツ語',
'ko': '독일어',
'pt': 'Alemão',
'ru': 'немецкий',
'es': 'Alemán',
} +
{
'en': Strings.hiLocale,
'zh': '印地语',
'de': 'Hindi',
'hi': 'हिंदी',
'id': 'Hindi',
'ja': 'ヒンディー語',
'ko': '힌디어',
'pt': 'Hindi',
'ru': 'хинди',
'es': 'Hindi',
} +
{
'en': Strings.idLocale,
'zh': '印度尼西亚',
'de': 'Indonesisch',
'hi': 'इन्डोनेशियाई',
'id': 'bahasa Indonesia',
'ja': 'インドネシア語',
'ko': '인도네시아어',
'pt': 'Indonésio',
'ru': 'индонезийский',
'es': 'Indonesio',
} +
{
'en': Strings.jaLocale,
'zh': '日本',
'de': 'japanisch',
'hi': 'जापानी',
'id': 'Jepang',
'ja': '日本語',
'ko': '일본어',
'pt': 'Japonês',
'ru': 'японский',
'es': 'Japonés',
} +
{
'en': Strings.koLocale,
'zh': '韩语',
'de': 'Koreanisch',
'hi': 'कोरियाई',
'id': 'Korea',
'ja': '韓国語',
'ko': '한국어',
'pt': 'Coreano',
'ru': 'корейский',
'es': 'Coreano',
} +
{
'en': Strings.ptLocale,
'zh': '葡萄牙语',
'de': 'Portugiesisch',
'hi': 'पुर्तगाली',
'id': 'Portugis',
'ja': 'ポルトガル語',
'ko': '포르투갈어',
'pt': 'Português',
'ru': 'португальский',
'es': 'Portugués',
} +
{
'en': Strings.ruLocale,
'zh': '俄语',
'de': 'Russisch',
'hi': 'रूसी',
'id': 'Rusia',
'ja': 'ロシア語',
'ko': '러시아어',
'pt': 'Russo',
'ru': 'русский',
'es': 'Ruso',
} +
{
'en': Strings.esLocale,
'zh': '西班牙文',
'de': 'Spanisch',
'hi': 'स्पेनिश',
'id': 'Orang Spanyol',
'ja': 'スペイン語',
'ko': '스페인어',
'pt': 'Espanhol',
'ru': 'испанский',
'es': 'Español',
} +
{
'en': Strings.signIn,
'zh': '登入',
'de': 'Anmelden',
'hi': 'साइन इन करें',
'id': 'Masuk',
'ja': 'サインイン',
'ko': '서명하세요',
'pt': 'Entrar',
'ru': 'Войти',
'es': 'Inicia sesión',
} +
{
'en': Strings.emailLabel,
'zh': '电子邮件',
'de': 'Email',
'hi': 'ईमेल',
'id': 'Surel',
'ja': '電子メール',
'ko': '이메일',
'pt': 'Email',
'ru': 'Электронная почта',
'es': 'Correo electrónico',
} +
{
'en': Strings.emailHint,
'zh': 'test@test.com',
'de': 'test@test.com',
'hi': 'test@test.com',
'id': 'test@test.com',
'ja': 'test@test.com',
'ko': 'test@test.com',
'pt': 'test@test.com',
'ru': 'test@test.com',
'es': 'test@test.com',
} +
{
'en': Strings.signInWithEmailLink,
'zh': '登入',
'de': 'Einloggen',
'hi': 'साइन इन करें',
'id': 'Masuk',
'ja': 'サインイン',
'ko': '서명하세요',
'pt': 'Entrar',
'ru': 'Войти',
'es': 'Inicia sesión',
} +
{
'en': Strings.invalidEmailErrorText,
'zh': '电邮无效',
'de': 'E-Mail ist ungültig',
'hi': 'ईमेल अमान्य है',
'id': 'email tidak valid',
'ja': '電子メールが無効です',
'ko': '이메일이 잘못되었습니다.',
'pt': 'O e-mail é inválido',
'ru': 'Электронная почта недействительна',
'es': 'El correo electrónico no es válido',
} +
{
'en': Strings.inspiredText,
'zh': '受到家人分享方式的启发',
'de': 'wurde von der Art und Weise inspiriert, wie Ihre Familie teilt',
'hi': 'जिस तरह से आपके परिवार के शेयरों से प्रेरित था',
'id': 'terinspirasi oleh cara keluarga Anda berbagi',
'ja': 'あなたの家族が共有する方法に触発されました',
'ko': '가족이 공유하는 방식에서 영감을 받았습니다.',
'pt': 'foi inspirado pela forma como sua família compartilha',
'ru': 'был вдохновлен тем, как ваша семья акций',
'es': 'se inspiró en la forma en que su familia comparte',
} +
{
'en': Strings.fromYouthAndOtherThings,
'zh': '来自他们的青年，高中，冒险，婚姻，军事，儿童等。',
'de': 'von ihrer Jugend, High School, Abenteuer, Ehe, Militär, Kinder, etc.',
'hi': 'अपनी जवानी, हाई स्कूल, रोमांच, शादी, सेना, बच्चों, आदि से।',
'id': 'dari masa muda, sekolah menengah, petualangan, pernikahan, militer, anak-anak, dll.',
'ja': '彼らの若さから, 高校, 冒険, 結婚, 軍隊, 子供, 等.',
'ko': '청소년, 고등학교, 모험, 결혼, 군인, 자녀 등',
'pt': 'de sua juventude, ensino médio, aventuras, casamento, militar, filhos, etc.',
'ru': 'с юности, средней школы, приключений, брака, военных, детей и т.д.',
'es': 'de su juventud, escuela secundaria, aventuras, matrimonio, militares, hijos, etc.',
} +
{
'en': Strings.memoriesText,
'zh': '照片的回忆',
'de': 'Erinnerungen an Fotos',
'hi': 'तस्वीरों की यादें',
'id': 'kenangan foto',
'ja': '写真の思い出',
'ko': '사진의 추억',
'pt': 'memórias de fotos',
'ru': 'воспоминания о фотографиях',
'es': 'recuerdos de fotos',
} +
{
'en': Strings.youCanShare,
'zh': '这样您就可以与家人共享了。',
'de': 'so dass Sie jetzt mit anderen in Ihrer Familie teilen können.',
'hi': 'ताकि आप अब अपने परिवार में दूसरों के साथ साझा कर सकें।',
'id': 'sehingga Anda sekarang dapat berbagi dengan orang lain di keluarga Anda.',
'ja': '家族の中で他の人と共有できるようにしましょう。',
'ko': '이제 가족 내 다른 사람들과 나눌 수 있게 됩니다.',
'pt': 'para que agora você possa compartilhar com outros de sua família.',
'ru': 'так что теперь вы можете поделиться с другими членами вашей семьи.',
'es': 'para que ahora puedas compartir con otras personas de tu familia.',
} +
{
'en': Strings.submitEmailAddressLink,
'zh': '提交您的电子邮件地址以接收激活链接。',
'de': 'Geben Sie Ihre E-Mail-Adresse ein, um einen Aktivierungslink zu erhalten.',
'hi': 'सक्रियण लिंक प्राप्त करने के लिए अपना ईमेल पता भेजें।',
'id': 'Kirimkan alamat email Anda untuk menerima link aktivasi.',
'ja': 'アクティベーションリンクを受信するには、メールアドレスを送信します。',
'ko': '활성화 링크를 받으려면 이메일 주소를 제출합니다.',
'pt': 'Envie seu endereço de e-mail para receber um link de ativação.',
'ru': 'Отправьте свой адрес электронной почты для получения ссылки активации.',
'es': 'Envíe su dirección de correo electrónico para recibir un enlace de activación.',
} +
{
'en': Strings.checkYourEmail,
'zh': '查看你的电子邮件',
'de': 'Überprüfen Sie Ihren Posteingang',
'hi': 'अपने ईमेल की जाँच करें',
'id': 'Periksa email Anda',
'ja': 'メールを確認する',
'ko': '이메일 확인',
'pt': 'Verifique seu e-mail',
'ru': 'Проверьте свою электронную почту',
'es': 'Revisa tu correo electrónico',
} +
{
'en': Strings.activationLinkSent,
'zh': '我们已发送激活链接',
'de': 'Wir haben einen Aktivierungslink gesendet',
'hi': 'हमने एक सक्रियण लिंक भेजा है',
'id': 'Kami telah mengirimkan tautan aktivasi',
'ja': 'アクティベーションリンクを送信しました',
'ko': '활성화 링크를 보냈습니다.',
'pt': 'Enviamos um link de ativação',
'ru': 'Мы отправили ссылку активации',
'es': 'Hemos enviado un enlace de activación',
} +
{
'en': Strings.errorSendingEmail,
'zh': '发送电子邮件时出错',
'de': 'Fehler beim Senden der E-Mail',
'hi': 'ईमेल भेजने में त्रुटि',
'id': 'Terjadi kesalahan saat mengirim email',
'ja': '電子メールの送信中にエラーが発生しました',
'ko': '이메일 전송 오류',
'pt': 'Erro de envio de e-mail',
'ru': 'Ошибка отправки электронной почты',
'es': 'Error al enviar correo electrónico',
} +
{
'en': Strings.sendActivationLink,
'zh': '发送激活链接',
'de': 'Aktivierungslink senden',
'hi': 'सक्रियण लिंक भेजें',
'id': 'Kirim tautan aktivasi',
'ja': 'アクティベーションリンクの送信',
'ko': '활성화 링크 보내기',
'pt': 'Enviar link de ativação',
'ru': 'Отправить ссылку активации',
'es': 'Enviar enlace de activación',
} +
{
'en': Strings.activationLinkError,
'zh': '电子邮件激活错误',
'de': 'E-Mail-Aktivierungsfehler',
'hi': 'ईमेल सक्रियण त्रुटि',
'id': 'Kesalahan aktivasi email',
'ja': '電子メールのアクティブ化エラー',
'ko': '이메일 활성화 오류',
'pt': 'Erro de ativação de e-mail',
'ru': 'Ошибка активации электронной почты',
'es': 'Error de activación por correo electrónico',
} +
{
'en': Strings.submitEmailAgain,
'zh': '请再次提交您的电子邮件地址，以接收新的激活链接。',
'de': 'Bitte senden Sie Ihre E-Mail-Adresse erneut, um einen neuen Aktivierungslink zu erhalten.',
'hi': 'नया सक्रियण लिंक प्राप्त करने के लिए कृपया अपना ईमेल पता पुनः सबमिट करें।',
'id': 'Harap kirimkan alamat email Anda lagi untuk menerima tautan aktivasi baru.',
'ja': '新しいアクティベーションリンクを受信するには、再度メールアドレスを送信してください。',
'ko': '새 활성화 링크를 받으려면 이메일 주소를 다시 제출하십시오.',
'pt': 'Envie seu endereço de e-mail novamente para receber um novo link de ativação.',
'ru': 'Пожалуйста, отправьте свой адрес электронной почты еще раз, чтобы получить новую ссылку активации.',
'es': 'Por favor, envíe su dirección de correo electrónico de nuevo para recibir un nuevo enlace de activación.',
} +
{
'en': Strings.userAlreadySignedIn,
'zh': '已收到激活链接，但您已经登录。',
'de': 'Sie haben einen Aktivierungslink erhalten, sind aber bereits angemeldet.',
'hi': 'एक सक्रियण लिंक प्राप्त किया, लेकिन आप पहले से साइन इन हैं।',
'id': 'Menerima tautan aktivasi tetapi Anda sudah masuk.',
'ja': 'アクティベーションリンクを受信しましたが、既にサインインしています。',
'ko': '활성화 링크를 받았지만 이미 로그인되었습니다.',
'pt': 'Recebeu um link de ativação, mas você já está lodo.',
'ru': 'Получена ссылка активации, но вы уже войкомиться.',
'es': 'Recibió un enlace de activación, pero ya ha iniciado sesión.',
} +
{
'en': Strings.isNotSignInWithEmailLinkMessage,
'zh': '无效的激活链接',
'de': 'Ungültiger Aktivierungslink',
'hi': 'अमान्य सक्रियण लिंक',
'id': 'Tautan aktivasi tidak valid',
'ja': '無効なアクティベーション リンク',
'ko': '잘못된 활성화 링크',
'pt': 'Link de ativação inválido',
'ru': 'Недействительная ссылка активации',
'es': 'Enlace de activación no válido',
} +
{
'en': Strings.toolTipFAB,
'zh': '添加故事',
'de': 'Story hinzufügen',
'hi': 'कहानी जोड़ें',
'id': 'Tambahkan Cerita',
'ja': 'ストーリーの追加',
'ko': '스토리 추가',
'pt': 'Adicionar história',
'ru': 'Добавить историю',
'es': 'Añadir historia',
} +
{
'en': Strings.storiesTabName,
'zh': '故事',
'de': 'Geschichten',
'hi': 'कहानियों',
'id': 'Cerita',
'ja': '物語',
'ko': '이야기',
'pt': 'Histórias',
'ru': 'Истории',
'es': 'Historias',
} +
{
'en': Strings.friendsTabName,
'zh': '用户数',
'de': 'Benutzer',
'hi': 'उपयोगकर्ता',
'id': 'Pengguna',
'ja': 'ユーザー',
'ko': '사용자',
'pt': 'Usuários',
'ru': 'Пользователей',
'es': 'Usuarios',
} +
{
'en': Strings.noticesTabName,
'zh': '告示',
'de': 'Hinweise',
'hi': 'नोटिस',
'id': 'Pemberitahuan',
'ja': '通知',
'ko': '통지',
'pt': 'Avisos',
'ru': 'Уведомления',
'es': 'Avisos',
} +
{
'en': Strings.profileTabName,
'zh': '个人资料',
'de': 'Profil',
'hi': 'प्रोफ़ाइल',
'id': 'Profil',
'ja': 'プロファイル',
'ko': '프로필',
'pt': 'Perfil',
'ru': 'Профиль',
'es': 'Perfil',
} +
{
'en': Strings.filterText,
'zh': '按名称或家过滤',
'de': 'Filtern Sie nach Name oder Heimat',
'hi': 'नाम या घर से फ़िल्टर करें',
'id': 'Filter menurut nama atau rumah',
'ja': '名前または自宅でフィルタ',
'ko': '이름 또는 가정으로 필터링',
'pt': 'Filtrar pelo nome ou casa',
'ru': 'Фильтр по имени или дома',
'es': 'Filtrar por nombre o hogar',
} +
{
'en': Strings.typeUserButtonFriends,
'zh': '友人',
'de': 'Freunde',
'hi': 'दोस्त',
'id': 'Teman',
'ja': '友人',
'ko': '친구',
'pt': 'Amigos',
'ru': 'Друзей',
'es': 'Amigos',
} +
{
'en': Strings.typeUserButtonUsers,
'zh': '其他',
'de': 'Andere',
'hi': 'अन्य',
'id': 'Lainnya',
'ja': '他',
'ko': '다른',
'pt': 'Outros',
'ru': 'Другие',
'es': 'Otros',
} +
{
'en': Strings.typeUserButtonMe,
'zh': '我',
'de': 'Mich',
'hi': 'मुझे',
'id': 'Saya',
'ja': '私',
'ko': '나',
'pt': 'Me',
'ru': 'Меня',
'es': 'Yo',
} +
{
'en': Strings.requestFriendship,
'zh': '请求友谊？',
'de': 'Freundschaft anfordern?',
'hi': 'दोस्ती का अनुरोध?',
'id': 'Minta Persahabatan?',
'ja': '友情を要求しますか?',
'ko': '우정을 요청?',
'pt': 'Pedir amizade?',
'ru': 'Запросить дружбу?',
'es': '¿Pedir amistad?',
} +
{
'en': Strings.cancelFriendship,
'zh': '结束友谊？',
'de': 'Freundschaft beenden?',
'hi': 'दोस्ती खत्म?',
'id': 'Akhiri Persahabatan?',
'ja': '友情を終わらせる?',
'ko': '우정을 끝내시나요?',
'pt': 'Acabar com a amizade?',
'ru': 'Прекратить дружбу?',
'es': '¿Acabar con la amistad?',
} +
{
'en': Strings.quitFriend,
'zh': '退出朋友？',
'de': 'Freund verlassen?',
'hi': 'दोस्त छोड़ो?',
'id': 'Keluar dari teman?',
'ja': '友達をやめる?',
'ko': '친구를 그만두시나요?',
'pt': 'Largar amigo?',
'ru': 'Бросить друга?',
'es': '¿Dejar de amigo?',
} +
{
'en': Strings.pending,
'zh': '待定',
'de': 'steht aus',
'hi': 'विचाराधीन',
'id': 'Menunggu keputusan',
'ja': '保留 中',
'ko': '보류 중인',
'pt': 'Pendente',
'ru': 'Ожидающие',
'es': 'Pendiente',
} +
{
'en': Strings.newFriend,
'zh': '朋友吗',
'de': 'Freund?',
'hi': 'दोस्त?',
'id': 'Teman?',
'ja': '友人。',
'ko': '친구?',
'pt': 'Amigo?',
'ru': 'Друг?',
'es': '¿Amigo?',
} +
{
'en': Strings.rejectFriendshipRequest,
'zh': '拒绝友谊请求？',
'de': 'Freundschaftsanfrage ablehnen?',
'hi': 'रिक्वेस्ट फ्रेंडशिप रिक्वेस्ट?',
'id': 'Tolak Permintaan Pertemanan?',
'ja': '友情の要求を拒否しますか?',
'ko': '우정 요청을 거부?',
'pt': 'Rejeitar o pedido de amizade?',
'ru': 'Отклонить запрос о дружбе?',
'es': '¿Rechazar la solicitud de amistad?',
} +
{
'en': Strings.approveFriendshipRequest,
'zh': '批准友谊请求？',
'de': 'Freundschaftsanfrage genehmigen?',
'hi': 'मित्रता के अनुरोध को स्वीकार करें?',
'id': 'Setujui Permintaan Pertemanan?',
'ja': 'フレンドシップリクエストを承認しますか?',
'ko': '우정 요청을 승인합니까?',
'pt': 'Aprovar o pedido de amizade?',
'ru': 'Утвердить запрос на дружбу?',
'es': '¿Aprobar la solicitud de amistad?',
} +
{
'en': Strings.approveFriendButton,
'zh': '批准',
'de': 'Genehmigen',
'hi': 'मंजूर',
'id': 'Menyetujui',
'ja': '承認',
'ko': '승인',
'pt': 'Aprovar',
'ru': 'Утвердить',
'es': 'Aprobar',
} +
{
'en': Strings.rejectFriendButton,
'zh': '拒绝',
'de': 'Ablehnen',
'hi': 'अस्वीकार',
'id': 'Menolak',
'ja': '拒否',
'ko': '거부',
'pt': 'Rejeitar',
'ru': 'Отклонить',
'es': 'Rechazar',
} +
{
'en': Strings.viewCommentButton,
'zh': '视图',
'de': 'Aussicht',
'hi': 'राय',
'id': 'Melihat',
'ja': 'ビュー',
'ko': '보기',
'pt': 'Ver',
'ru': 'Вид',
'es': 'Vista',
} +
{
'en': Strings.clearCommentButton,
'zh': '明确',
'de': 'klar',
'hi': 'स्पष्ट',
'id': 'Bersih',
'ja': 'クリア',
'ko': '명확한',
'pt': 'Claro',
'ru': 'Ясно',
'es': 'Claro',
} +
{
'en': Strings.profilePageName,
'zh': '个人资料',
'de': 'Profil',
'hi': 'प्रोफ़ाइल',
'id': 'Profil',
'ja': 'プロファイル',
'ko': '프로필',
'pt': 'Perfil',
'ru': 'Профиль',
'es': 'Perfil',
} +
{
'en': Strings.galleryImageButton,
'zh': '画廊',
'de': 'Galerie',
'hi': 'गेलरी',
'id': 'Galeri',
'ja': 'ギャラリー',
'ko': '갤러리',
'pt': 'Galeria',
'ru': 'Галерея',
'es': 'Galería',
} +
{
'en': Strings.cameraImageButton,
'zh': '相机',
'de': 'Kamera',
'hi': 'कैमरा',
'id': 'Kamera',
'ja': 'カメラ',
'ko': '카메라',
'pt': 'Câmera',
'ru': 'Камеры',
'es': 'Cámara',
} +
{
'en': Strings.imagePlaceholderText,
'zh': '您的图片占位符',
'de': 'Ihr Bildplatzhalter',
'hi': 'आपकी छवि प्लेसहोल्डर',
'id': 'Placeholder Gambar Anda',
'ja': 'イメージプレースホルダー',
'ko': '이미지 자리 표시자',
'pt': 'Seu espaço reservado de imagem',
'ru': 'Заполнитель изображений',
'es': 'Su marcador de posición de imagen',
} +
{
'en': Strings.yourPictureSelection,
'zh': '您的图片选择',
'de': 'Ihre Bildauswahl',
'hi': 'आपका चित्र चयन',
'id': 'Pilihan gambar Anda',
'ja': '画像の選択',
'ko': '사진 선택',
'pt': 'Sua seleção de fotos',
'ru': 'Ваш выбор фотографий',
'es': 'Su selección de imagen',
} +
{
'en': Strings.yourFullNameText,
'zh': '输入您的全名',
'de': 'Geben Sie Ihren vollständigen Namen ein',
'hi': 'अपना पूरा नाम लिखे',
'id': 'Masukkan nama lengkapmu',
'ja': '氏名を入力してください',
'ko': '전체 이름 입력',
'pt': 'Digite seu nome completo',
'ru': 'Введите свое полное имя',
'es': 'Introduzca su nombre completo',
} +
{
'en': Strings.yourFullNameLabel,
'zh': '名称',
'de': 'Name',
'hi': 'नाम',
'id': 'Nama',
'ja': '名前',
'ko': '이름',
'pt': 'Nome',
'ru': 'Имя',
'es': 'Nombre',
} +
{
'en': Strings.yourHomeText,
'zh': '输入您的城市，州',
'de': 'Geben Sie Ihre Stadt, Bundesland',
'hi': 'अपना शहर, राज्य दर्ज करें',
'id': 'Masukkan kota Anda, negara bagian',
'ja': 'あなたの都市、州を入力してください',
'ko': '도시, 주',
'pt': 'Entre em sua cidade, estado',
'ru': 'Войдите в свой город, штат',
'es': 'Ingrese su ciudad, estado',
} +
{
'en': Strings.yourHomeLabel,
'zh': '家',
'de': 'Zuhause',
'hi': 'घर',
'id': 'Rumah',
'ja': 'ホーム',
'ko': '홈',
'pt': 'Casa',
'ru': 'Дома',
'es': 'Casa',
} +
{
'en': Strings.yourBirthText,
'zh': '出生年',
'de': 'Geburtsjahr',
'hi': 'जन्म वर्ष',
'id': 'Tahun lahir',
'ja': '出生年',
'ko': '출생 연도',
'pt': 'Ano de nascimento',
'ru': 'Год рождения',
'es': 'Año de nacimiento',
} +
{
'en': Strings.yourBirthLabel,
'zh': '你的出生年份',
'de': 'Jahr Ihrer Geburt',
'hi': 'आपके जन्म का वर्ष',
'id': 'Tahun kelahiranmu',
'ja': 'あなたの誕生年',
'ko': '출생의 해',
'pt': 'Ano de seu nascimento',
'ru': 'Год вашего рождения',
'es': 'Año de su nacimiento',
} +
{
'en': Strings.nameEmptyMessage,
'zh': '请输入你的名字',
'de': 'Bitte geben Sie Ihren Namen ein',
'hi': 'अपना नाम दर्ज करें',
'id': 'Silahkan masukan nama anda',
'ja': '名前を入力してください',
'ko': '이름을 입력해 주세요',
'pt': 'Por favor, digite seu nome',
'ru': 'Пожалуйста, введите свое имя',
'es': 'Por favor, introduzca su nombre',
} +
{
'en': Strings.homeEmptyMessage,
'zh': '请进入你的家',
'de': 'Bitte geben Sie Ihr Zuhause ein',
'hi': 'कृपया अपने घर में प्रवेश करें',
'id': 'Silakan masuk rumah Anda',
'ja': 'ご自宅をご入力ください',
'ko': '집에 들어가주세요',
'pt': 'Por favor, entre em sua casa.',
'ru': 'Пожалуйста, введите свой дом',
'es': 'Por favor, ingrese a su casa',
} +
{
'en': Strings.birthEmptyMessage,
'zh': '请输入年份',
'de': 'Bitte geben Sie ein Jahr ein',
'hi': 'कृपया एक वर्ष दर्ज करें',
'id': 'Harap masukkan satu tahun',
'ja': '年を入力してください',
'ko': '1년 을 입력하십시오.',
'pt': 'Por favor, entre em um ano',
'ru': 'Пожалуйста, введите год',
'es': 'Por favor, introduzca un año',
} +
{
'en': Strings.birthValidationMessage,
'zh': '请输入有效年份',
'de': 'Bitte ein gültiges Jahr eingeben',
'hi': 'कृपया सुयोग्य साल दर्ज करे',
'id': 'Harap masukkan tahun yang valid',
'ja': '有効な年を入力してください',
'ko': '유효한 연도를 입력하십시오.',
'pt': 'Por favor, entre em um ano válido',
'ru': 'Пожалуйста, введите действительный год',
'es': 'Por favor, introduzca un año válido',
} +
{
'en': Strings.imagePlaceholder,
'zh': '图片占位符',
'de': 'Platzhalter fuer Bild',
'hi': 'छवि प्लेसहोल्डर',
'id': 'Placeholder Gambar',
'ja': 'イメージプレースホルダー',
'ko': '이미지 자리 표시자',
'pt': 'Espaço reservado para imagem',
'ru': 'Правообладатель иллюстрации Image',
'es': 'Marcador de posición de imagen',
} +
{
'en': Strings.imageSelection,
'zh': '图像选择',
'de': 'Bildauswahl',
'hi': 'छवि चयन',
'id': 'Pemilihan Gambar',
'ja': '画像の選択',
'ko': '이미지 선택',
'pt': 'Seleção de imagens',
'ru': 'Выбор изображений',
'es': 'Selección de imagen',
} +
{
'en': Strings.currentAudio,
'zh': '音讯',
'de': 'Audio',
'hi': 'ऑडियो',
'id': 'Audio',
'ja': 'オーディオ',
'ko': '오디오',
'pt': 'Áudio',
'ru': 'Аудио',
'es': 'Audio',
} +
{
'en': Strings.audioControls,
'zh': '记录故事',
'de': 'Geschichte aufnehmen',
'hi': 'रिकॉर्ड कहानी',
'id': 'Rekam Cerita',
'ja': 'レコードストーリー',
'ko': '레코드 스토리',
'pt': 'História de Registro',
'ru': 'История записи',
'es': 'Record Story',
} +
{
'en': Strings.pictureGallery,
'zh': '画廊',
'de': 'Galerie',
'hi': 'गेलरी',
'id': 'Galeri',
'ja': 'ギャラリー',
'ko': '갤러리',
'pt': 'Galeria',
'ru': 'Галерея',
'es': 'Galería',
} +
{
'en': Strings.pictureCamera,
'zh': '相机',
'de': 'Kamera',
'hi': 'कैमरा',
'id': 'Kamera',
'ja': 'カメラ',
'ko': '카메라',
'pt': 'Câmera',
'ru': 'Камеры',
'es': 'Cámara',
} +
{
'en': Strings.audioStop,
'zh': '停止',
'de': 'Halt',
'hi': 'रुकें',
'id': 'Berhenti',
'ja': '停止',
'ko': '중지',
'pt': 'Parar',
'ru': 'Остановить',
'es': 'Parada',
} +
{
'en': Strings.audioPlay,
'zh': '玩',
'de': 'abspielen',
'hi': 'खेल',
'id': 'Bermain',
'ja': '再生',
'ko': '재생',
'pt': 'Jogar',
'ru': 'Играть',
'es': 'Jugar',
} +
{
'en': Strings.audioRecord,
'zh': '记录',
'de': 'Aufzeichnung',
'hi': 'अभिलेख',
'id': 'Merekam',
'ja': 'レコード',
'ko': '레코드',
'pt': 'Registro',
'ru': 'Записи',
'es': 'grabar',
} +
{
'en': Strings.audioPause,
'zh': '暂停',
'de': 'Pause',
'hi': 'ठहराव',
'id': 'Berhenti sebentar',
'ja': '一時 停止',
'ko': '일시 중지',
'pt': 'Pausa',
'ru': 'Пауза',
'es': 'Pausa',
} +
{
'en': Strings.audioResume,
'zh': '恢复',
'de': 'Weitermachen',
'hi': 'बायोडाटा',
'id': 'Lanjut',
'ja': '再開',
'ko': '이력서',
'pt': 'Currículo',
'ru': 'Возобновить',
'es': 'Reanudar',
} +
{
'en': Strings.audioClear,
'zh': '明确',
'de': 'klar',
'hi': 'स्पष्ट',
'id': 'Bersih',
'ja': 'クリア',
'ko': '명확한',
'pt': 'Claro',
'ru': 'Ясно',
'es': 'Claro',
} +
{
'en': Strings.mustAcceptPermissions,
'zh': '您必须接受权限',
'de': 'Sie müssen Berechtigungen akzeptieren',
'hi': 'आपको परमिशन लेनी चाहिए',
'id': 'Anda harus menerima izin',
'ja': 'アクセス許可を受け入れる必要があります',
'ko': '사용 권한을 수락해야 합니다.',
'pt': 'Você deve aceitar permissões',
'ru': 'Вы должны принимать разрешения',
'es': 'Debe aceptar permisos',
} +
{
'en': Strings.addTagHere,
'zh': '在此处添加标签',
'de': 'Tag hier hinzufügen',
'hi': 'यहां टैग लगाएं',
'id': 'Tambahkan tag di sini',
'ja': 'ここにタグを追加',
'ko': '여기에 태그 추가',
'pt': 'Adicionar tag aqui',
'ru': 'Добавить тег здесь',
'es': 'Añadir etiqueta aquí',
} +
{
'en': Strings.showAllTags,
'zh': '显示所有标签',
'de': 'Alle Tags anzeigen',
'hi': 'सभी टैग दिखाएं',
'id': 'Tampilkan semua tag',
'ja': 'すべてのタグを表示',
'ko': '모든 태그 표시',
'pt': 'Mostre todas as tags',
'ru': 'Показать все теги',
'es': 'Mostrar todas las etiquetas',
} +
{
'en': Strings.deleteStoryButton,
'zh': '删除故事？',
'de': 'Geschichte löschen?',
'hi': 'कहानी हटाएं?',
'id': 'Hapus cerita?',
'ja': 'ストーリーを削除しますか?',
'ko': '스토리를 삭제?',
'pt': 'Apagar a história?',
'ru': 'Удалить историю?',
'es': '¿Eliminar historia?',
} +
{
'en': Strings.incrementToolTip,
'zh': '添加故事',
'de': 'Story hinzufügen',
'hi': 'कहानी जोड़ें',
'id': 'Tambahkan Cerita',
'ja': 'ストーリーの追加',
'ko': '스토리 추가',
'pt': 'Adicionar história',
'ru': 'Добавить историю',
'es': 'Añadir historia',
} +
{
'en': Strings.gridStoryShowCommentsText,
'zh': '有％条评论',
'de': 'Es gibt% Kommentare',
'hi': '% कमेंट हैं',
'id': 'Ada% komentar',
'ja': '% コメントがあります',
'ko': '% 의견이 있습니다.',
'pt': 'Há % comentários',
'ru': 'Есть % комментариев',
'es': 'Hay % de comentarios',
} +
{
'en': Strings.gridStoryShowTagsText,
'zh': '有％标签',
'de': 'Es gibt% Tags',
'hi': '% टैग हैं',
'id': 'Ada% tag',
'ja': '% タグがあります',
'ko': '% 태그가 있습니다.',
'pt': 'Existem % tags',
'ru': 'Есть % тегов',
'es': 'Hay % de etiquetas',
} +
{
'en': Strings.friendRequest,
'zh': '好友请求',
'de': 'Frage von einem Freund',
'hi': 'मित्र अनुरोध',
'id': 'Permintaan pertemanan',
'ja': 'フレンドリクエスト',
'ko': '친구 요청',
'pt': 'Solicitação de Amigo',
'ru': 'Запрос на друга',
'es': 'Solicitud de amigo',
} +
{
'en': Strings.commentRequest,
'zh': '新评论',
'de': 'Neuer Kommentar',
'hi': 'नई टिप्पणी',
'id': 'Komentar Baru',
'ja': '新しいコメント',
'ko': '새 댓글',
'pt': 'Novo Comentário',
'ru': 'Новый комментарий',
'es': 'Nuevo comentario',
} +
{
'en': Strings.developerMenu,
'zh': '开发者菜单',
'de': 'Entwicklermenü',
'hi': 'डेवलपर मेनू',
'id': 'Menu pengembang',
'ja': '開発者メニュー',
'ko': '개발자 메뉴',
'pt': 'Menu do desenvolvedor',
'ru': 'Меню разработчика',
'es': 'Menú Desarrollador',
} +
{
'en': Strings.authenticationType,
'zh': '认证方式',
'de': 'Authentifizierungsart',
'hi': 'प्रमाणिकता का प्रकार',
'id': 'Jenis Autentikasi',
'ja': '認証の種類',
'ko': '인증 유형',
'pt': 'Tipo de autenticação',
'ru': 'Тип аутентификации',
'es': 'Tipo de autenticación',
} +
{
'en': Strings.firebase,
'zh': '火力基地',
'de': 'Feuerbasis',
'hi': 'Firebase',
'id': 'Firebase',
'ja': 'ファイアベース',
'ko': '파이어베이스',
'pt': 'Base de fogo',
'ru': 'Пожарная база',
'es': 'Firebase',
} +
{
'en': Strings.mock,
'zh': '嘲笑',
'de': 'Spotten',
'hi': 'दिखावटी',
'id': 'Mengejek',
'ja': 'モック',
'ko': '모의',
'pt': 'Mock',
'ru': 'Макет',
'es': 'Simulacro',
} +
{
'en': Strings.recordAComment,
'zh': '记录评论',
'de': 'Nimm einen Kommentar auf',
'hi': 'एक टिप्पणी रिकॉर्ड करें',
'id': 'Rekam komentar',
'ja': 'コメントを記録する',
'ko': '댓글 녹음',
'pt': 'Registo um comentário',
'ru': 'Запись комментария',
'es': 'Grabar un comentario',
} +
{
'en': Strings.commentsLabel,
'zh': '评论',
'de': 'Bemerkungen',
'hi': 'टिप्पणियाँ',
'id': 'Komentar',
'ja': 'コメント',
'ko': '코멘트',
'pt': 'Comentários',
'ru': 'Комментарии',
'es': 'Comentarios',
} +
{
'en': Strings.storyLabel,
'zh': '故事',
'de': 'Geschichte',
'hi': 'कहानी',
'id': 'Cerita',
'ja': '話',
'ko': '이야기',
'pt': 'História',
'ru': 'Строй',
'es': 'Historia',
} +
{
'en': Strings.deleteStoryQuestion,
'zh': '删除故事？',
'de': 'Story löschen?',
'hi': 'डिलीट स्टोरी?',
'id': 'Hapus Cerita?',
'ja': 'ストーリーを削除しますか?',
'ko': '스토리를 삭제?',
'pt': 'Apagar história?',
'ru': 'Удалить историю?',
'es': '¿Eliminar historia?',
} +
{
'en': Strings.dateLabel,
'zh': '日期',
'de': 'Datum',
'hi': 'तारीख',
'id': 'Tanggal',
'ja': '日付',
'ko': '날짜',
'pt': 'Data',
'ru': 'Дата',
'es': 'Fecha',
} +
{
'en': Strings.tagsLabel,
'zh': '标签',
'de': 'Stichworte',
'hi': 'टैग',
'id': 'Tag',
'ja': 'タグ',
'ko': '태그',
'pt': 'Tags',
'ru': 'Теги',
'es': 'Etiquetas',
} +
{
'en': Strings.searchByTagsHint,
'zh': '按标签搜索',
'de': 'Suche nach Tag',
'hi': 'टैग द्वारा खोजें',
'id': 'Cari berdasarkan tag',
'ja': 'タグで検索',
'ko': '태그로 검색',
'pt': 'Pesquisar por tag',
'ru': 'Поиск по тегам',
'es': 'Buscar por etiqueta',
} +
{
'en': Strings.deleteComment,
'zh': '删除',
'de': 'Löschen',
'hi': 'हटाएं',
'id': 'Menghapus',
'ja': '削除',
'ko': '삭제',
'pt': 'Excluir',
'ru': 'Удалить',
'es': 'Eliminar',
} +
{
'en': Strings.hideComment,
'zh': '隐藏',
'de': 'Ausblenden',
'hi': 'छिपाना',
'id': 'Menyembunyikan',
'ja': '隠す',
'ko': '숨기기',
'pt': 'Esconder',
'ru': 'Скрыть',
'es': 'Ocultar',
} +
{
'en': Strings.showComment,
'zh': '显示',
'de': 'Show',
'hi': 'प्रदर्शन',
'id': 'Menunjukkan',
'ja': '表示',
'ko': '표시',
'pt': 'programa',
'ru': 'Показать',
'es': 'Mostrar',
} +
